#!/bin/sh
export JMX_PORT=${JMX_PORT:-3008}
export JAVA_HOME=/usr/lib/jvm/java-6-oracle-amd64

base_dir=/opt/kafka-0.7.1

CLASSPATH=$CLASSPATH:/opt/kafka-0.7.1/config/log4j.properties

for file in $base_dir/libs/*.jar;
do
  CLASSPATH=$CLASSPATH:$file
done

if [ -z "$KAFKA_JMX_OPTS" ]; then
  KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=3008 -Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false "
fi
if [ -z "$KAFKA_OPTS" ]; then
  KAFKA_OPTS="-Xmx512M -server  -Dlog4j.configuration=file:$base_dir/config/log4j.properties"
fi
if [  $JMX_PORT ]; then
  KAFKA_JMX_OPTS="$KAFKA_JMX_OPTS -Dcom.sun.management.jmxremote.port=$JMX_PORT "
fi
if [ -z "$JAVA_HOME" ]; then
  JAVA="java"
else
  JAVA="$JAVA_HOME/bin/java"
fi



exec 2>&1
exec chpst -u hadoop $JAVA $KAFKA_OPTS $KAFKA_JMX_OPTS -cp $CLASSPATH kafka.Kafka /opt/kafka-0.7.1/config/server.properties

#exec chpst -u hadoop /opt/kafka-0.7.1/bin/kafka-run-class.sh kafka.Kafka /opt/kafka-0.7.1/config/server.properties

