# This file contains Lucid's default rules, as specified in the default solrconfig.xml
# The default configuration uses this rules file in one place:
#   1. The RulesComponent configured to run before all other SearchComponents (there is also
#       one configured to run after all other components, except debug.
#
# Rule writers may rely on, when using the RulesComponent the fact that
# the name of the "handler" (specified in the configuration) will be available as part of the Request context (request.getContext().get("rulesHandler")) along
# with the phase the component is in (prepare or process -- getContext().get("rulesPhase")) such that rules can be written that target a specific
# handler and/or a specific phase.
#
#
package rules;

#Some common imports
import org.apache.solr.handler.component.ResponseBuilder;
import function gaia.rules.drools.DroolsHelper.*;
import org.apache.solr.common.SolrDocument;
import org.apache.lucene.search.Query;
import org.apache.solr.common.params.SolrParams;
import org.apache.solr.common.params.ModifiableSolrParams;

import org.slf4j.Logger;
global org.slf4j.Logger logger;

